project:
  type: website
  output-dir: docs

website:
  title: "Mostly Monte Carlo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: psc_rooms.qmd
        text: Directions
  sidebar:
    style: "docked"
    search: true
    contents:
      - sem/s2024_05.qmd
      - sem/s2024_04.qmd
      - sem/s2024_03.qmd
      - sem/s2024_02.qmd
      - sem/s2024_01.qmd
      - sem/s2023_12.qmd
      - sem/s2023_11.qmd
      - sem/s2023_10.qmd
  page-navigation: true

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

