project:
  type: website
  output-dir: docs

website:
  title: "Mostly Monte Carlo"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: psc_rooms.qmd
        text: Directions
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "2025"
        href: sem/summary_2025.qmd
        contents:
          - sem/2025/s2025_01.qmd
          - sem/2025/s2025_02.qmd
          - sem/2025/s2025_03.qmd
          - sem/2025/s2025_04.qmd
          - sem/2025/s2025_05.qmd
      - section: "2024"
        href: sem/summary_2024.qmd
        contents:
          - sem/2024/s2024_01.qmd
          - sem/2024/s2024_02.qmd
          - sem/2024/s2024_03.qmd
          - sem/2024/s2024_04.qmd
          - sem/2024/s2024_04_sp.qmd
          - sem/2024/s2024_05.qmd
          - sem/2024/s2024_09.qmd
          - sem/2024/s2024_10.qmd
          - sem/2024/s2024_11.qmd
          - sem/2024/s2024_12.qmd
      - section: "2023"
        href: sem/summary_2023.qmd
        contents:
          - sem/2023/s2023_10.qmd
          - sem/2023/s2023_11.qmd
          - sem/2023/s2023_12.qmd
  page-navigation: true

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

