---
  title: "November"
  date: "2025-11-13 16:00"
  published-title: "Time and date"
  date-format: "hA dddd, MMM D, YYYY"
---

[Salle 08](../../psc_rooms.qmd), [PariSanté Campus](https://maps.app.goo.gl/cpFoxoZgbT6HCV6x9)

------------------------------------------------------------------------

::: callout-tip
## Seminar time

This seminar is scheduled on a **Thursday** at **4PM** 
:::


### Bilinear mixed models and variational inference

**[Omiros Papaspiliopoulos](https://faculty.unibocconi.eu/omirospapaspiliopoulos/)** *Universita' Bocconi*

The talk relates to a book I am currently writing with a political scientist, Max Goplerud (Austin), and deals with variational inference and its applications to large scale inference for generalized bilinear mixed models. This model structure is pervasive throughout applied sciences and includes as special cases generalized linear mixed models, matrix factorization models and item response theory. I will provide a synthesis of our methodological, theoretical and software work in this framework and link to other works and results in the field.


### A coupling-based approach to f-divergences diagnostics for Markov chain Monte Carlo

**[Adrien Corenflos](https://adriencorenflos.github.io/)** *University of Warwick*

Joint work with Hai-Dang Dau. Available on [arXiv](https://arxiv.org/abs/2510.07559).

A long-standing gap exists between the theoretical analysis of Markov chain Monte Carlo convergence, which is often based on statistical divergences, and the diagnostics used in practice. We introduce the first general convergence diagnostics for Markov chain Monte Carlo based on any f-divergence, allowing users to directly monitor, among others, the Kullback--Leibler and the Chi-squared divergences as well as the Hellinger and the total variation distances. Our first key contribution is a coupling-based `weight harmonization' scheme that produces a direct, computable, and consistent weighting of interacting Markov chains with respect to their target distribution. The second key contribution is to show how such consistent weightings of empirical measures can be used to provide upper bounds to f-divergences in general. We prove that these bounds are guaranteed to tighten over time and converge to zero as the chains approach stationarity, providing a concrete diagnostic. Numerical experiments demonstrate that our method is a practical and competitive diagnostic tool.